RIP-dz/PlansList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('accounts/', include('account.urls', namespace = 'account')),
]

RIP-dz/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('reg/', views.AccountRegistrationView.as_view(), name='reg'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('about/<str:username>/', views.AboutProfileView.as_view(), name='about'),
    path('edit/', views.EditProfileView.as_view(), name='edit')
]

RIP-dz/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='home'),
    path('<int:pk>/<slug:slug>/', views.TaskDetailView.as_view(), name='task_detail'),

    path('addevent/', views.AddEventView.as_view(), name='addevent'),

    path('success-event/<int:id>/', views.success_event, name='success-event')
]

RIP-dz/account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    status = models.CharField(max_length=200, blank=True, verbose_name='Статус')
    photo = models.ImageField(upload_to='static/img/users/%Y', blank=True, verbose_name='Аватарка',
                              default='/static/img/profile_default.jpg')

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = 'Профили'

    def __str__(self):
        return '{}'.format(self.user.username)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

RIP-dz/account/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'status', 'photo')

RIP-dz/account/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic.edit import CreateView
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .forms import UserForm, ProfileForm
from django.contrib.auth.models import User


# Create your views here.
class AccountRegistrationView(CreateView):
    template_name = 'registration/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('main:home')
    extra_context = {'title': 'Мой список дел | Регистрация'}

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        return result


class AboutProfileView(View, LoginRequiredMixin):
    template_name = 'profile/about.html'

    def get(self,request, username, *args, **kwargs):
        return render(request, self.template_name, {
            'user': User.objects.get(username=username),
            'title': 'Мой список дел | Профиль'
        })


class EditProfileView(View, LoginRequiredMixin):
    template_name = 'profile/edit.html'

    def get(self,request, *args, **kwargs):
        user = UserForm(instance=request.user)
        profile = ProfileForm(instance=request.user.profile)
        return render(request, self.template_name, {
            'user_form': user,
            'profile_form': profile,
            'title': 'Мой список дел | Изменить'
        })

    def post(self,request, *args, **kwargs):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        print(user_form,profile_form)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('account:about', request.user.username)

RIP-dz/account/templates/profile/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container about">
        <div class="row">
            <div class="col-4 offset-2">
                <div class="avatar-img">
                    {% if user.profile.photo.url  %}
                        <img src="/{{ user.profile.photo.url }}" alt="Аватарка">
                    {% endif %}
                </div>
            </div>
            <div class="col-4">
                {% if user.first_name and user.last_name %}
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                {% else %}
                    <h2>Имя и фамилия не указаны</h2>
                {% endif %}
                {% if user.profile.status %}
                    Статус: <span class="" style="color: green">{{ user.profile.status }}</span>
                {% endif %}
                <p class="text-muted">username: {{ user.username }}</p>
                {% if user.email %}
                    <p>{{ user.email }}</p>
                {% else %}
                    <p>email не указан</p>
                {% endif %}
                {% if user.profile.date_of_birth %}
                    <p>Дата рождения: {{ user.profile.date_of_birth }}</p>
                {% else %}
                    <p>Дата рождения не указана</p>
                {% endif %}
            <a href="{% url 'account:edit' %}" class="btn btn-light" style="box-shadow: 0 0 3px var(--shadow);">Изменить</a>
            </div>
        </div>
    </div>
{% endblock %}

RIP-dz/account/templates/profile/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container about">
        <div class="row">
            <div class="col-4 offset-2 input-img-hover" style="height: 210px">
                <div class="avatar-img">
                    <img src="/{{ user.profile.photo.url }}" alt="Аватарка">
                </div>
            </div>
            <div class="col-5">
                <form method="post" class="edit" action="{% url 'account:edit' %}" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" class="btn btn-light" style="box-shadow: 0 0 3px var(--shadow);" value="Изменить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}